version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    command: node ./dist/server/entry.mjs
